### ISSUE TITLE
Corrigir consulta cliente com id inexistente

### ISSUE THREAD

**Issue by oliveiralex** [giselli/devsuperior-tarefa1#1]
Olá Giselli, tudo bem? Sou o Alexandre e estou corrigindo a sua atividade.

Trabalho aceito, parabéns! Para ficar 100% eu sugiro, incluir o tratamento de exceções. Ao consultar (GET) um cliente com id inexistente retorna um erro 500.

Abraço e bons estudos

**Comment by giselli** [comment]
Boa noite! Acho que consegui resolver o problema: ad352e26b798192924cd7e2a922003393761688a
